console.log(1<4)
console.log(1>4)
console.log(5<5)
console.log(5==5)
console.log(4>=1)
console.log(10!=8)
console.log(6==6)

console.log("====StringComaprsion====")
console.log("Hari">"Shiva")
console.log("Shiva">"Sai")
console.log("Sai">"SaiRam")
